### ISSUE TITLE
Issue with LeftRightMulCVO structure

### ISSUE THREAD

**Issue by lvchien** [krcools/ConvolutionOperators.jl#2]
LeftRightMulCVO structure does not support CompositeMap as left_linear_map or right_linear_map. This raises an issue when multiplying  2 linear maps to the left or the right sides of the Convop. The issue is actually with the timeslice! function, which does not return a matrix.

**Comment by krcools** [comment]
Can you provide an example?

**Comment by lvchien** [comment]
@krcools: I am using BEAST.jl. Let's suppose `LLM` a composite map of 2 linear maps, `lhs` a ConvOp. I would like to get the first time slice matrix of the ConvOp `LLM * lhs`.

```
lhs′ = LLM * lhs
T = eltype(lhs)
Z0 = zeros(T, size(lhs)[1:2])
ConvolutionOperators.timeslice!(Z0, lhs′, 1)
```
**Error: MethodError: no method matching iterate**

**Comment by krcools** [comment]
Right, the problem is that timeslice produces a Matrix, so explicit casting is required for LinearMaps. I applied a quick but efficient patch to this. Please try on master.

**Comment by lvchien** [comment]
Thank you very much!
